### ISSUE TITLE
Time::Piece dependency missing

### ISSUE THREAD

**Issue by abraxxa** [reneeb/DBIx-Class-InflateColumn-TimePiece#2]

**Comment by reneeb** [comment]
This should be already fixed in version 0.02...
https://github.com/reneeb/DBIx-Class-InflateColumn-TimePiece/blob/7c8a72a78f87dba9a6e5d6a76f828e4c7ddea2bb/dist.ini#L55

Did you test version 0.01?

**Comment by abraxxa** [comment]
I looked yesterday when the 0.01 release was announced in #dbix-class and checked today if a new version is available but I must have looked before 0.02 was indexed by metacpan.
